### ISSUE TITLE
sometimes data is missing from the first(today) object in array

### ISSUE THREAD

**Issue by em222iv** [evanshortiss/yr.no-forecast#8]
<img width="309" alt="missing data" src="https://user-images.githubusercontent.com/5379414/28533423-5a974536-709d-11e7-8626-7acd41aa6a9c.png">

As this image is showing. I'm getting the problem the the first object sometimes lack the data which it commonly has, and the other objects still has.

**Comment by evanshortiss** [comment]
@em222iv, did you find anymore information on this? Is it a bug in this module or simply an intricacy of the yr.no service XML? What parameters are you passing in the call?

**Comment by evanshortiss** [comment]
@em222iv bump - let me know if you can provide more information so we can determine if this is a bug in the module or a quirk of the yr.no service.
